# Generated by Django 4.0.4 on 2022-05-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja_sub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decade',
            name='start_year',
            field=models.CharField(max_length=100),
        ),
    ]
