# Generated by Django 4.0.4 on 2022-05-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nost', '0003_auto_20220503_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fads',
            new_name='Fad',
        ),
    ]
