# Generated by Django 4.0.4 on 2022-05-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fad',
            name='description',
            field=models.TextField(),
        ),
    ]
