# Generated by Django 4.0.4 on 2022-05-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_auto_20220503_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fad',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fad',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
