# Generated by Django 4.0.4 on 2022-05-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_auto_20220504_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fad',
            name='description',
            field=models.CharField(default='description', max_length=1000),
        ),
    ]
