# Generated by Django 4.0.4 on 2022-05-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0003_alter_fad_description'),
        ('nostaldja', '0004_auto_20220504_0057'),
    ]

    operations = [
    ]
