# Generated by Django 4.0.4 on 2022-05-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0005_merge_20220504_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decade',
            name='start_year',
            field=models.CharField(max_length=100),
        ),
    ]
