# Generated by Django 4.0.4 on 2022-05-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_decade_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='decade',
            name='comments',
            field=models.TextField(default='No comments.'),
        ),
    ]
