# Generated by Django 4.1 on 2022-08-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Decade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Fad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img_url", models.TextField()),
                ("description", models.TextField()),
                (
                    "decade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fads",
                        to="u4_lab_nostaldja.decade",
                    ),
                ),
            ],
        ),
    ]
